name: Register Julia package on private registry
description: Like Registrator but for federated registries

branding:
  icon: 'package'
  color: 'purple'

inputs:
  registry:
    description: Repository of the private registry
    required: true
  subdirectory:
    description: Subdirectory of the repository where the package lives
    required: required
    default: '.'
  name:
    description: Name of the account requesting the registration
    required: true
    default: '${{ github.actor }}'
  email:
    description: Email address of the account requesting the PR registration
    required: true
    default: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
  push:
    description: If true, push to a custom branch in the registry
    required: true
    default: true
  branch:
    description: If `inputs.push=true`, branch where the registering package will be uploaded.
    required: false
outputs:
  name:
    description: Project name
    value: ${{ steps.register-package.outputs.name }}
  uuid:
    description: Project UUID
    value: ${{ steps.register-package.outputs.uuid }}
  version:
    description: Project version
    value: ${{ steps.register-package.outputs.version }}
  hash:
    description: Tree hash of the registering package
    value: ${{ steps.register-package.outputs.hash }}
  branch:
    description: If `inputs.push=true`, branch where the registering package will be uploaded
    value: ${{ steps.register-package.outputs.branch }}
  path:
    description: Path to the local registry.
    value: ${{ steps.register-package.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: julia --color=yes --project=${{ github.action_path }} {0}
      run: |
        using Pkg
        Pkg.instantiate()
    - name: Register package
      id: register-package
      shell: bash
      run: julia --color=yes --project='${{ github.action_path }}' '${{ github.action_path }}/register.jl' '${{ inputs.subdirectory }}' '${{ inputs.registry }}' '${{ inputs.name }}' '${{ inputs.email }}' '${{ inputs.push }}' '${{ github.actor }}'
